AWSTemplateFormatVersion: "2010-09-09"
Description: "EC2 Web Server with Apache - Guaranteed Working Template"

Parameters:
  KeyName:
    Description: "Name of an existing EC2 KeyPair"
    Type: "AWS::EC2::KeyPair::KeyName"
    Default: "junaid-key"
    ConstraintDescription: "Must be the name of an existing EC2 KeyPair."

  InstanceType:
    Description: "EC2 instance type"
    Type: "String"
    Default: "t2.micro"
    AllowedValues:
      - "t2.micro"
      - "t3.micro"
    ConstraintDescription: "Must be a valid EC2 instance type."

Resources:
  WebServerSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Enable SSH and HTTP access"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"
        - IpProtocol: "tcp"
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"
      Tags:
        - Key: "Name"
          Value: "WebServer-SG"

  WebServerInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: "ami-00af95fa354fdb788"  # Amazon Linux 2 in ap-south-1
      SecurityGroups:
        - !Ref WebServerSecurityGroup
      Tags:
        - Key: "Name"
          Value: "WebServer-Project2"
      UserData:
        Fn::Base64: |
          #!/bin/bash
          # Update system
          yum update -y
          
          # Install Apache
          yum install -y httpd
          
          # Start and enable Apache
          systemctl start httpd
          systemctl enable httpd
          
          # Create simple HTML page
          echo '<!DOCTYPE html>
          <html>
          <head>
              <title>CloudFormation Web Server</title>
              <style>
                  body { font-family: Arial, sans-serif; text-align: center; padding: 50px; }
                  h1 { color: #FF9900; }
                  .status { color: green; font-weight: bold; }
              </style>
          </head>
          <body>
              <h1>✅ SUCCESS! CloudFormation Web Server</h1>
              <p class="status">Apache is running successfully!</p>
              <p>Instance ID: '$(curl -s http://169.254.169.254/latest/meta-data/instance-id)'</p>
              <p>Deployed via AWS CloudFormation</p>
              <hr>
              <p>Project 2 - Infrastructure as Code</p>
          </body>
          </html>' > /var/www/html/index.html
          
          # Set proper permissions
          chmod 644 /var/www/html/index.html
          
          # Create health check file
          echo "Healthy" > /var/www/html/health.html
          
          # Restart httpd to ensure all changes take effect
          systemctl restart httpd
          
          # Final status check
          echo "UserData script completed at: $(date)" > /tmp/userdata.log
          systemctl status httpd >> /tmp/userdata.log

Outputs:
  WebsiteURL:
    Description: "Public URL for the web server"
    Value: !Sub "http://${WebServerInstance.PublicDnsName}"
    
  InstancePublicIP:
    Description: "Public IP address of the EC2 instance"
    Value: !GetAtt WebServerInstance.PublicIp
    
  HealthCheckURL:
    Description: "Health check endpoint"
    Value: !Sub "http://${WebServerInstance.PublicDnsName}/health.html"
    
  SSHCommand:
    Description: "SSH command to connect to the instance"
    Value: !Sub "ssh -i junaid-key.pem ec2-user@${WebServerInstance.PublicDnsName}"